name: wade

services:

  db:
    image: pgvector/pgvector:pg17
    platform: linux/amd64
    container_name: "mrvn-pgvector-pg17"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: wade
      POSTGRES_USER: postgres

  localstack:
    image: localstack/localstack:4.12.0
    container_name: "mrvn-localstack-4.12.0"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs

  wait:
    image: waisbrot/wait
    depends_on:
      - localstack
      - db
    environment:
      - TARGETS=localstack:4566,db:5432
