name: mrvn

services:

  db:
    image: postgres:17
    container_name: "mrvn-postgres-17"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mrvn
      POSTGRES_USER: postgres

  localstack:
    image: localstack/localstack:4.3.0
    container_name: "mrvn-localstack-4.3.0"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs

  wait:
    image: waisbrot/wait
    depends_on:
      - localstack
      - db
    environment:
      - TARGETS=localstack:4566,db:5432